<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(0,17,1,'54Ot6Zeo6K++56iL');
$cfg_Cs[3]=array(2,17,1,'SmF2YQ==');
$cfg_Cs[4]=array(2,17,1,'5aSn5pWw5o2u');
$cfg_Cs[5]=array(2,17,1,'5Lq65bel5pm66IO9');
$cfg_Cs[6]=array(2,17,1,'5YiG57G75Zub');
$cfg_Cs[7]=array(0,18,1,'6Z+p6aG65bmz5Zui6Zif');
$cfg_Cs[8]=array(0,1,1,'5LyY56eA5a2m5ZGY');
$cfg_Cs[9]=array(0,1,1,'5Zyo57q/5oql5ZCN');
$cfg_Cs[10]=array(0,1,1,'6K++56iL5pyN5Yqh');
$cfg_Cs[11]=array(0,1,1,'5pyA5paw6YCa55+l');
$cfg_Cs[12]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[13]=array(0,1,1,'5pWZ5a2m546v5aKD');
$cfg_Cs[14]=array(0,1,1,'5LyB5Lia5YaF5o6o');
?>