<?php
$z[0]=Array("field","",181,210);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",235,264);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n            <li> <a href=\"[field:arcurl/]\">\r\n              <div class=\"img\"><img src=\"[field:litpic/]\"/>\r\n                <div class=\"img_text\"><!--<span>[field:title/]</span>--><span></span>\r\n                  <!--<p>工资： ([field:shorttitle/])</p>--><p></p>\r\n                </div>\r\n              </div>\r\n              <div class=\"text\">\r\n                <p>[field:description function='cn_substr(@me,122)'/]...</p>\r\n              </div>\r\n              </a> </li>\r\n            ",433,987);
$z[2][4]=array();
$z[2][4]['row']="6";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("field","",1061,1089);
$z[3][4]=array();
$z[3][4]['name']="typeurl";

?>