<?php
$z[0]=Array("arcurl","",50,65);
$z[0][4]=array();
$z[1]=Array("litpic","",78,93);
$z[1][4]=array();
$z[2]=Array("arcurl","",180,195);
$z[2][4]=array();
$z[3]=Array("global","(@me==1)? @me=\"<span>最新</span>\":@me=\"\";",197,297);
$z[3][4]=array();
$z[3][4]['name']="autoindex";
$z[3][4]['runphp']="yes";
$z[4]=Array("title","",297,311);
$z[4][4]=array();
$z[5]=Array("description","",347,397);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,300)";
$z[6]=Array("typename","",465,482);
$z[6][4]=array();
$z[7]=Array("pubdate","",507,552);
$z[7][4]=array();
$z[7][4]['function']="MyDate('Y-m-d',@me)";

?>