<?php
$z[0]=Array("litpic","",96,111);
$z[0][4]=array();
$z[1]=Array("zjr","",235,247);
$z[1][4]=array();
$z[2]=Array("arcurl","",546,561);
$z[2][4]=array();
$z[3]=Array("title","",563,577);
$z[3][4]=array();
$z[4]=Array("kcxx","\r\n                        \$arr = explode(',',@me);\r\n                        \$result = '';\r\n                        for(\$index=0;\$index<count(\$arr);\$index++){\r\n    \$result .= \"<label>\$arr[\$index]</label>\";\r\n}\r\n@me = \$result;\r\n",637,898);
$z[4][4]=array();
$z[4][4]['runphp']="yes";
$z[5]=Array("description","",955,1005);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,160)";
$z[6]=Array("arcurl","",1018,1033);
$z[6][4]=array();

?>