<li> <a href="[field:arcurl/]">
              <div class="img"><img src="[field:litpic/]"/>
                <div class="img_text"><span>[field:title/]</span>
                  <p>工资： ([field:shorttitle/]元)</p>
                </div>
              </div>
              <div class="text">
                <p>[field:description function='cn_substr(@me,120)'/]...</p>
              </div>
              </a> </li>