<li> <a href="[field:arcurl/]">
                    <div class="img1"> <img src="[field:litpic/]"/> [field:array runphp=yes]
                    ($GLOBALS[autoindex]<=3) ? @me="<span class='sp1'>":@me="<span>";
                      [/field:array][field:global name=autoindex/]</span> </div>
                    <div class="web">
                    <h4>[field:title/] </h4>
                    <p>上传：[field:pubdate function=MyDate('Y-m-d',@me)/]</p>
                  </div>
                    <div class="clear"></div>
                    </a> </li>