<?php
$z[0]=Array("global","",132,158);
$z[0][4]=array();
$z[0][4]['name']="cfg_cmspath";
$z[1]=Array("channel","\r\n          <li><a href=\"[field:typeurl/]\">[field:typename/]\r\n            <label></label>\r\n            </a></li>\r\n          ",237,546);
$z[1][4]=array();
$z[1][4]['type']="top";
$z[1][4]['currentstyle']="<li><a href='~typelink~' class='thisclass'>~typename~ <label></label> </a></li>";
$z[2]=Array("global","",638,660);
$z[2][4]=array();
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",698,722);
$z[3][4]=array();
$z[3][4]['name']="cfg_email";
$z[4]=Array("flink","  [field:link /]  ",790,868);
$z[4][4]=array();
$z[4][4]['titlelen']="20";
$z[4][4]['row']="20";
$z[4][4]['type']="text";
$z[5]=Array("global","",929,955);
$z[5][4]=array();
$z[5][4]['name']="cfg_powerby";
$z[6]=Array("global","",1014,1038);
$z[6][4]=array();
$z[6][4]['name']="cfg_beian";
$z[7]=Array("global","",1372,1394);
$z[7][4]=array();
$z[7][4]['name']="cfg_tel";

?>