<?php
$z[0]=Array("global","",73,94);
$z[0][4]=array();
$z[0][4]['name']="cfg_gg";
$z[1]=Array("global","",223,249);
$z[1][4]=array();
$z[1][4]['name']="cfg_cmspath";
$z[2]=Array("global","",382,408);
$z[2][4]=array();
$z[2][4]['name']="cfg_cmspath";
$z[3]=Array("type","\r\n          <li><span><a href=\"[field:typelink/]\">[field:typename/]</a></span></li>\r\n          ",485,614);
$z[3][4]=array();
$z[3][4]['typeid']="9";
$z[4]=Array("global","",799,825);
$z[4][4]=array();
$z[4][4]['name']="cfg_cmspath";
$z[5]=Array("global","",838,864);
$z[5][4]=array();
$z[5][4]['name']="cfg_cmspath";
$z[6]=Array("global","",941,963);
$z[6][4]=array();
$z[6][4]['name']="cfg_tel";
$z[7]=Array("field","(@me==\"\")? @me=\" class='on'\":@me=\"\";",1144,1230);
$z[7][4]=array();
$z[7][4]['name']="typeid";
$z[7][4]['runphp']="yes";
$z[8]=Array("global","",1240,1266);
$z[8][4]=array();
$z[8][4]['name']="cfg_cmspath";
$z[9]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/]\r\n          <label></label>\r\n          </a></li>\r\n        ",1339,1625);
$z[9][4]=array();
$z[9][4]['type']="top";
$z[9][4]['currentstyle']="<li class='on'><a href='~typelink~'>~typename~ <label></label> </a></li>";

?>