<li>
                <div class="top">
                      <div class="img1"> <img src="[field:litpic/]"/> </div>
                      <div class="web">
                    <h3>[field:title/]</h3>
                    <p>[field:byyx/]</p>
                  </div>
                      <div class="clear"></div>
                    </div>
                <div class="text">
                      <p>[field:description function='cn_substr(@me,120)'/]...</p>
                    </div>
              </li>