<?php
$z[0]=Array("field","",180,209);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",234,263);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n            <div class=\"item\"> <a target=\"_blank\" href=\"[field:arcurl/]\">\r\n              <div class=\"img\"><img src=\"[field:litpic/]\"/></div>\r\n              <div class=\"text\">\r\n                <h3>[field:global name=autoindex runphp=\"yes\"](@me==1)? @me=\"\r\n                  <label>最新</label>\r\n                  \":@me=\"\";[/field:global]<span>[field:title/] </span></h3>\r\n                <p>[field:description function='cn_substr(@me,80)'/]...</p>\r\n                <div class=\"bottom\"> <span class=\"span1\">[field:typename/]</span> <span class=\"span2\">[field:pubdate function=MyDate('Y-m-d',@me)/]</span> </div>\r\n              </div>\r\n              </a> </div>\r\n            ",425,1162);
$z[2][4]=array();
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("field","",1226,1254);
$z[3][4]=array();
$z[3][4]['name']="typeurl";

?>