<?php
$z[0]=Array("arcurl","",30,45);
$z[0][4]=array();
$z[1]=Array("litpic","",99,114);
$z[1][4]=array();
$z[2]=Array("kcxx","\r\n                                  \$arr = explode(',',@me);\r\n                                  \$result = '';\r\n                                  for(\$index=0;\$index<count(\$arr);\$index++){\r\n                                  \$result .= \"\$arr[\$index]  \";\r\n                                  }\r\n                                  @me = \$result;\r\n                                  ",199,609);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[3]=Array("arcurl","",833,848);
$z[3][4]=array();
$z[4]=Array("title","",850,864);
$z[4][4]=array();
$z[5]=Array("bm","",904,915);
$z[5][4]=array();
$z[6]=Array("writer","",931,946);
$z[6][4]=array();

?>