<?php
$z[0]=Array("field","",177,206);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n            <li> <a href=\"[field:arcurl/]\">\r\n              <div class=\"img\"><img src=\"[field:litpic/]\"/>\r\n                <div class=\"img_text\"><span>[field:title/]</span>\r\n                  <p>工资： ([field:shorttitle/])</p>\r\n                </div>\r\n              </div>\r\n              <div class=\"text\">\r\n                <p>[field:description function='cn_substr(@me,122)'/]...</p>\r\n              </div>\r\n              </a> </li>\r\n            ",375,895);
$z[1][4]=array();
$z[1][4]['row']="6";
$z[1][4]['titlelen']="50";
$z[1][4]['orderby']="pubdate";
$z[2]=Array("field","",969,997);
$z[2][4]=array();
$z[2][4]['name']="typeurl";

?>