<?php
$z[0]=Array("arcurl","",111,126);
$z[0][4]=array();
$z[1]=Array("litpic","",138,153);
$z[1][4]=array();
$z[2]=Array("zjr","",280,292);
$z[2][4]=array();
$z[3]=Array("arcurl","",591,606);
$z[3][4]=array();
$z[4]=Array("title","",608,622);
$z[4][4]=array();
$z[5]=Array("kcxx","\r\n                        \$arr = explode(',',@me);\r\n                        \$result = '';\r\n                        for(\$index=0;\$index<count(\$arr);\$index++){\r\n    \$result .= \"<label>\$arr[\$index]</label>\";\r\n}\r\n@me = \$result;\r\n",682,943);
$z[5][4]=array();
$z[5][4]['runphp']="yes";
$z[6]=Array("description","",1000,1050);
$z[6][4]=array();
$z[6][4]['function']="cn_substr(@me,160)";
$z[7]=Array("arcurl","",1063,1078);
$z[7][4]=array();
$z[8]=Array("arcurl","",1289,1304);
$z[8][4]=array();

?>