<?php
$z[0]=Array("arcurl","",111,126);
$z[0][4]=array();
$z[1]=Array("arcurl","",140,155);
$z[1][4]=array();
$z[2]=Array("litpic","",162,177);
$z[2][4]=array();
$z[3]=Array("zjr","",304,316);
$z[3][4]=array();
$z[4]=Array("arcurl","",615,630);
$z[4][4]=array();
$z[5]=Array("title","",632,646);
$z[5][4]=array();
$z[6]=Array("kcxx","\r\n                        \$arr = explode(',',@me);\r\n                        \$result = '';\r\n                        for(\$index=0;\$index<count(\$arr);\$index++){\r\n    \$result .= \"<label>\$arr[\$index]</label>\";\r\n}\r\n@me = \$result;\r\n",706,967);
$z[6][4]=array();
$z[6][4]['runphp']="yes";
$z[7]=Array("description","",1024,1074);
$z[7][4]=array();
$z[7][4]['function']="cn_substr(@me,160)";
$z[8]=Array("arcurl","",1087,1102);
$z[8][4]=array();
$z[9]=Array("arcurl","",1313,1328);
$z[9][4]=array();

?>