<?php
$z[0]=Array("arcurl","",66,81);
$z[0][4]=array();
$z[1]=Array("litpic","",94,109);
$z[1][4]=array();
$z[2]=Array("arcurl","",196,211);
$z[2][4]=array();
$z[3]=Array("global","(@me==1)? @me=\"<span>最新</span>\":@me=\"\";",213,313);
$z[3][4]=array();
$z[3][4]['name']="autoindex";
$z[3][4]['runphp']="yes";
$z[4]=Array("title","",313,327);
$z[4][4]=array();
$z[5]=Array("description","",363,413);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,300)";
$z[6]=Array("typename","",481,498);
$z[6][4]=array();
$z[7]=Array("pubdate","",523,568);
$z[7][4]=array();
$z[7][4]['function']="MyDate('Y-m-d',@me)";

?>