<?php
$z[0]=Array("global","(@me%2==0)? @me='frt':@me='flt';",39,128);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("litpic","",141,156);
$z[1][4]=array();
$z[2]=Array("global","(@me%2==0)? @me='flt':@me='frt';",200,289);
$z[2][4]=array();
$z[2][4]['name']="autoindex";
$z[2][4]['runphp']="yes";
$z[3]=Array("global","",359,389);
$z[3][4]=array();
$z[3][4]['name']="autoindex";
$z[4]=Array("title","",390,404);
$z[4][4]=array();
$z[5]=Array("title","",481,495);
$z[5][4]=array();
$z[6]=Array("description","",596,646);
$z[6][4]=array();
$z[6][4]['function']="cn_substr(@me,650)";

?>