<div class="page page2">
          <div class="wrap">
        <div class="page_tit  animated more-fast" data-animation="fadeInLeft">
              <h3>在线教育<span>·{dede:field name='typename'/}</span></h3>
              <p></p>
            </div>
        <div class="team_owl animated fast" data-animation="fadeInUp">
              <div class="owl"> {dede:arclist titlelen='50' orderby='pubdate' addfields='byyx' channelid='18'}
            <div class="item"> <a href="[field:arcurl/]">
              <div class="img"><img src="[field:litpic/]"/>
                <p>[field:byyx/]</p>
              </div>
              <div class="text">
                <h3>[field:title/]</h3>
                <p>[field:description function='cn_substr(@me,150)'/]...</p>
              </div>
              </a> </div>
            {/dede:arclist} </div>
            </div>
      </div>
        </div>