<?php
$z[0]=Array("field","",174,203);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n            <div class=\"item\"> <a href=\"[field:arcurl/]\">\r\n              <div class=\"img\"><img src=\"[field:litpic/]\"/>\r\n                <p>[field:byyx/]</p>\r\n              </div>\r\n              <div class=\"text\">\r\n                <h3>[field:title/]</h3>\r\n                <p>[field:description function='cn_substr(@me,150)'/]...</p>\r\n              </div>\r\n              </a> </div>\r\n            ",364,853);
$z[1][4]=array();
$z[1][4]['titlelen']="50";
$z[1][4]['orderby']="pubdate";
$z[1][4]['addfields']="byyx";
$z[1][4]['channelid']="18";

?>