<?php
$z[0]=Array("top","\r\n  <m:item name='网站栏目管理' link='catalog_main.php' ischannel='1' addalt='创建栏目' linkadd='catalog_add.php?listtype=all' rank='t_List,t_AccList' target='main' />\r\n\r\n  <m:item name='所有档案列表' link='content_list.php' rank='a_List,a_AccList' target='main' />\r\n  <m:item name='内容模型管理'  link='mychannel_main.php' rank='c_List' target='main' />\r\n  <m:item name='TAG标签管理' link='tags_main.php' rank='sys_Keyword' target='main' />\r\n  \r\n  \r\n",53,591);
$z[0][4]=array();
$z[0][4]['item']="1_";
$z[0][4]['name']="内容管理";
$z[0][4]['display']="block";
$z[1]=Array("top","\r\n  \r\n  <m:item name='一键更新网站' link='makehtml_all.php' rank='sys_MakeHtml' target='main' />\r\n  <m:item name='更新系统缓存' link='sys_cache_up.php' rank='sys_ArcBatch' target='main' />\r\n  <m:item name='更新主页HTML' link='makehtml_homepage.php' rank='sys_MakeHtml' target='main' />\r\n  <m:item name='更新栏目HTML' link='makehtml_list.php' rank='sys_MakeHtml' target='main' />\r\n  <m:item name='更新文档HTML' link='makehtml_archives.php' rank='sys_MakeHtml' target='main' />\r\n  \r\n",595,1161);
$z[1][4]=array();
$z[1][4]['item']="1_";
$z[1][4]['name']="生成管理";
$z[1][4]['display']="block";
$z[2]=Array("top","\r\n  <m:item name='系统基本参数' link='sys_info.php' rank='sys_Edit' target='main' />\r\n  <m:item name='系统用户管理' link='sys_admin_user.php' rank='sys_User' target='main' />\r\n  <m:item name='数据库备份/还原' link='sys_data.php' rank='sys_Data' target='main' />\r\n  <m:item name='验证安全设置' link='sys_safe.php' rank='sys_verify' target='main' />\r\n  <m:item name='图片水印设置' link='sys_info_mark.php' rank='sys_Edit' target='main' />\r\n  <m:item name='自定义文档属性' link='content_att.php' rank='sys_Att' target='main' />\r\n  <m:item name='SQL命令行工具' link='sys_sql_query.php' rank='sys_Data' target='main' />\r\n",1165,1884);
$z[2][4]=array();
$z[2][4]['item']="1_";
$z[2][4]['name']="系统设置";
$z[2][4]['display']="none";
$z[3]=Array("top","\r\n  <m:item name='幻灯片管理' link='ppt_main.php' rank='c_List' target='main'/>\r\n  <m:item name='广告位管理' link='ad_main.php' rank='c_List' target='main'/>\r\n  <m:item name='自定义表单' link='diy_main.php' rank='c_List' target='main'/>\r\n  <m:item name='默认模板管理' link='templets_main.php' rank='c_List' target='main'/>\r\n  <m:item name='内容模型管理' link='mychannel_main.php' rank='c_List' target='main'/>\r\n  <m:item name='搜索关键词维护' link='search_keywords_main.php' rank='c_List' target='main'/>\r\n  <m:item name='文档关键词维护' link='article_keywords_main.php' rank='sys_Keyword' target='main' />\r\n  <m:item name='重复文档检测' link='article_test_same.php' rank='sys_ArcBatch' target='main' />\r\n  <m:item name='友情链接管理' link='friendlink_main.php' rank='c_List' target='main'/>\r\n",1892,2798);
$z[3][4]=array();
$z[3][4]['item']="1_";
$z[3][4]['name']="网站运维";
$z[3][4]['display']="none";
$z[4]=Array("top","\r\n  <m:item name='模块管理' link='module_main.php' rank='sys_module' target='main' />\r\n  <m:item name='上传新模块' link='module_upload.php' rank='sys_module' target='main' />\r\n  <m:item name='模块生成向导' link='module_make.php' rank='sys_module' target='main' />\r\n  <m:item name='插件管理器' link='plus_main.php' rank='10' target='main' />\r\n",2810,3240);
$z[4][4]=array();
$z[4][4]['item']="1_";
$z[4][4]['name']="模块管理";
$z[4][4]['c']="6,";
$z[4][4]['display']="block";
$z[5]=Array("top","\r\n<m:item name='德得模块' link='mda_main.php' rank='plus_广告管理' target='main'/>\r\n<m:item name='广告管理' link='mda_main.php?dopost=place' rank='plus_广告管理' target='main'/>\r\n<m:item name='查看报表' link='mda_main.php?dopost=report' rank='plus_广告管理' target='main'/>\r\n<m:item name='结算中心' link='mda_main.php?dopost=account' rank='plus_广告管理' target='main'/>\r\n<m:item name='德得设置' link='mda_main.php?dopost=setting' rank='plus_广告管理' target='main'/>\r\n",3244,3815);
$z[5][4]=array();
$z[5][4]['item']="1_";
$z[5][4]['name']="德得广告";
$z[5][4]['display']="block";

?>