<?php
$z[0]=Array("arcurl","",30,45);
$z[0][4]=array();
$z[1]=Array("litpic","",91,106);
$z[1][4]=array();
$z[2]=Array("kcxx","\r\n                    \$arr = explode(',',@me);\r\n                    \$result = '';\r\n                    for(\$index=0;\$index<count(\$arr);\$index++){\r\n    \$result .= \"\$arr[\$index]  \";\r\n}\r\n@me = \$result;\r\n",169,405);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[3]=Array("arcurl","",599,614);
$z[3][4]=array();
$z[4]=Array("title","",616,630);
$z[4][4]=array();
$z[5]=Array("bm","",664,675);
$z[5][4]=array();
$z[6]=Array("writer","",693,708);
$z[6][4]=array();

?>