<?php
$z[0]=Array("arcurl","",99,114);
$z[0][4]=array();
$z[1]=Array("litpic","",126,141);
$z[1][4]=array();
$z[2]=Array("zjr","",268,280);
$z[2][4]=array();
$z[3]=Array("arcurl","",579,594);
$z[3][4]=array();
$z[4]=Array("title","",596,610);
$z[4][4]=array();
$z[5]=Array("kcxx","\r\n                        \$arr = explode(',',@me);\r\n                        \$result = '';\r\n                        for(\$index=0;\$index<count(\$arr);\$index++){\r\n    \$result .= \"<label>\$arr[\$index]</label>\";\r\n}\r\n@me = \$result;\r\n",670,931);
$z[5][4]=array();
$z[5][4]['runphp']="yes";
$z[6]=Array("description","",988,1038);
$z[6][4]=array();
$z[6][4]['function']="cn_substr(@me,160)";
$z[7]=Array("arcurl","",1051,1066);
$z[7][4]=array();
$z[8]=Array("arcurl","",1277,1292);
$z[8][4]=array();

?>