
<field:name itemname="真实姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:tel itemname="手机号码" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>

<field:qq itemname="QQ号码" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:qq>

<field:xb itemname="性别" autofield="1" type="radio" isnull="true" default="男生,女生"  maxlength="250" page="">
</field:xb>
