<li>
                <div class="img1 [field:global name=autoindex runphp="yes"](@me%2==0)? @me='frt':@me='flt';[/field:global]"> <img src="[field:litpic/]"/> </div>
                <div class="web [field:global name=autoindex runphp="yes"](@me%2==0)? @me='flt':@me='frt';[/field:global]">
                      <div class="tit">
                    <h3>0[field:global name=autoindex/]</h3>
                    <span></span>
                    <h4>[field:title/]</h4>
                  </div>
                      <div class="text">
                    <p>[field:description function='cn_substr(@me,650)'/]</p>
                  </div>
                    </div>
                <div class="clear"></div>
              </li>