<?php
$z[0]=Array("arcurl","",14,29);
$z[0][4]=array();
$z[1]=Array("litpic","",75,90);
$z[1][4]=array();
$z[2]=Array("kcxx","\r\n                    \$arr = explode(',',@me);\r\n                    \$result = '';\r\n                    for(\$index=0;\$index<count(\$arr);\$index++){\r\n    \$result .= \"\$arr[\$index] / \";\r\n}\r\n@me = \$result;\r\n",153,390);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[3]=Array("arcurl","",568,583);
$z[3][4]=array();
$z[4]=Array("title","",585,599);
$z[4][4]=array();
$z[5]=Array("bm","",629,640);
$z[5][4]=array();
$z[6]=Array("writer","",656,671);
$z[6][4]=array();
$z[7]=Array("bm","",671,682);
$z[7][4]=array();

?>