<li> <a href="[field:arcurl/]">
              <div class="img"> <img src="[field:litpic/]"/>
                <div class="text">
                  <p> [field:kcxx runphp=yes]
                    $arr = explode(',',@me);
                    $result = '';
                    for($index=0;$index<count($arr);$index++){
    $result .= "$arr[$index] / ";
}
@me = $result;
[/field:kcxx]
                  
                  </p>
                </div>
              </div>
              </a>
                  <div class="web">
                <h4><a href="[field:arcurl/]">[field:title/]</a></h4>
                <p>[field:bm/]人 报名<span>[field:writer/][field:bm/]人</span></p>
              </div>
                </li>