<?php
$z[0]=Array("channel","\r\n                  <li [field:global name=autoindex runphp=\"yes\"](@me==0)? @me=\"class='on'\":@me=\"\";[/field:global]><a href=\"javascript:void(0)\">[field:typename/]</a></li>\r\n                  ",97,439);
$z[0][4]=array();
$z[0][4]['type']="son";
$z[0][4]['currentstyle']="<li class='on'><a href='~typelink~'>~typename~</a></li>";
$z[1]=Array("field","",519,547);
$z[1][4]=array();
$z[1][4]['name']="typeurl";

?>