<?php
$z[0]=Array("arcurl","",28,43);
$z[0][4]=array();
$z[1]=Array("litpic","",88,103);
$z[1][4]=array();
$z[2]=Array("global","(@me==1)? @me=\"\r\n                  <label>最新</label>\r\n                  \":@me=\"\";",168,310);
$z[2][4]=array();
$z[2][4]['name']="autoindex";
$z[2][4]['runphp']="yes";
$z[3]=Array("title","",316,330);
$z[3][4]=array();
$z[4]=Array("description","",364,413);
$z[4][4]=array();
$z[4][4]['function']="cn_substr(@me,80)";
$z[5]=Array("typename","",479,496);
$z[5][4]=array();
$z[6]=Array("pubdate","",524,569);
$z[6][4]=array();
$z[6][4]['function']="MyDate('Y-m-d',@me)";

?>