<?php
$z[0]=Array("arcurl","",66,81);
$z[0][4]=array();
$z[1]=Array("litpic","",94,109);
$z[1][4]=array();
$z[2]=Array("arcurl","",212,227);
$z[2][4]=array();
$z[3]=Array("global","(@me==1)? @me=\"<span>最新</span>\":@me=\"\";",229,329);
$z[3][4]=array();
$z[3][4]['name']="autoindex";
$z[3][4]['runphp']="yes";
$z[4]=Array("title","",329,343);
$z[4][4]=array();
$z[5]=Array("description","",379,429);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,300)";
$z[6]=Array("typename","",497,514);
$z[6][4]=array();
$z[7]=Array("pubdate","",539,584);
$z[7][4]=array();
$z[7][4]['function']="MyDate('Y-m-d',@me)";

?>