<?php
$z[0]=Array("arcurl","",14,29);
$z[0][4]=array();
$z[1]=Array("litpic","",82,97);
$z[1][4]=array();
$z[2]=Array("array","\r\n                    (\$GLOBALS[autoindex]<=3) ? @me=\"<span class='sp1'>\":@me=\"<span>\";\r\n                      ",101,250);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[3]=Array("global","",250,280);
$z[3][4]=array();
$z[3][4]['name']="autoindex";
$z[4]=Array("title","",359,373);
$z[4][4]=array();
$z[5]=Array("pubdate","",413,458);
$z[5][4]=array();
$z[5][4]['function']="MyDate('Y-m-d',@me)";

?>