<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	
<field:bm itemname="累计报名" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:bm>
<field:kcxx itemname="课程分类选项" autofield="1" notsend="0" type="checkbox" isnull="true" islist="0" default="新手入门,基础内容,实际操作,职称实战,架构师,源码剖析,消息中间件"  maxlength="250" page="">
</field:kcxx>
<field:zjr itemname="主讲人" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zjr>
