<li> <a target="_blank" href="[field:arcurl/]">
                  <div class="img"> <img src="[field:litpic/]"/> </div>
                  </a>
                      <div class="web">
                    <h4><a target="_blank" href="[field:arcurl/]">[field:title/]</a></h4>
                    <p>[field:bm/]人 报名<span>[field:writer/][field:bm/]人</span></p>
                  </div>
                    </li>