<?php
$z[0]=Array("arcurl","",111,126);
$z[0][4]=array();
$z[1]=Array("litpic","",139,154);
$z[1][4]=array();
$z[2]=Array("zjr","",256,268);
$z[2][4]=array();
$z[3]=Array("arcurl","",567,582);
$z[3][4]=array();
$z[4]=Array("title","",584,598);
$z[4][4]=array();
$z[5]=Array("kcxx","\r\n                        \$arr = explode(',',@me);\r\n                        \$result = '';\r\n                        for(\$index=0;\$index<count(\$arr);\$index++){\r\n    \$result .= \"<label>\$arr[\$index]</label>\";\r\n}\r\n@me = \$result;\r\n",658,919);
$z[5][4]=array();
$z[5][4]['runphp']="yes";
$z[6]=Array("description","",976,1026);
$z[6][4]=array();
$z[6][4]['function']="cn_substr(@me,160)";
$z[7]=Array("arcurl","",1039,1054);
$z[7][4]=array();
$z[8]=Array("arcurl","",1265,1280);
$z[8][4]=array();

?>