<?php
$z[0]=Array("field","",178,207);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",232,261);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n            <div class=\"item\"> <a target=\"_blank\" href=\"[field:arcurl/]\">\r\n              <div class=\"img\"><img src=\"[field:litpic/]\"/>\r\n                <p>[field:byyx/]</p>\r\n              </div>\r\n              <div class=\"text\">\r\n                <h3>[field:title/]</h3>\r\n                <p>[field:description function='cn_substr(@me,150)'/]...</p>\r\n              </div>\r\n              </a> </div>\r\n            ",422,927);
$z[2][4]=array();
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";
$z[2][4]['addfields']="byyx";
$z[2][4]['channelid']="18";

?>