<?php
$z[0]=Array("global","",132,158);
$z[0][4]=array();
$z[0][4]['name']="cfg_cmspath";
$z[1]=Array("channel","\r\n          <li><a target=\"_blank\" href=\"[field:typeurl/]\">[field:typename/]\r\n            <label></label>\r\n            </a></li>\r\n          ",237,578);
$z[1][4]=array();
$z[1][4]['type']="top";
$z[1][4]['currentstyle']="<li><a target=";
$z[1][4]['_blank" href']="~typelink~";
$z[1][4]['class']="thisclass";
$z[1][4]['>~typename~ <label></label> </a></li> "']="";
$z[2]=Array("global","",670,692);
$z[2][4]=array();
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",730,754);
$z[3][4]=array();
$z[3][4]['name']="cfg_email";
$z[4]=Array("flink","  [field:link /]  ",822,900);
$z[4][4]=array();
$z[4][4]['titlelen']="20";
$z[4][4]['row']="20";
$z[4][4]['type']="text";
$z[5]=Array("global","",961,987);
$z[5][4]=array();
$z[5][4]['name']="cfg_powerby";
$z[6]=Array("global","",1046,1070);
$z[6][4]=array();
$z[6][4]['name']="cfg_beian";
$z[7]=Array("global","",1408,1430);
$z[7][4]=array();
$z[7][4]['name']="cfg_tel";

?>