<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typenameen,typedir,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                                            FROM `dede_arctype` WHERE  id IN(2,2) AND ispart<>2 AND ishidden<>1  ORDER BY sortrank ASC LIMIT 20</font>
Time2021-01-31 22:31:12
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typenameen,typedir,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                                            FROM `dede_arctype` WHERE  reid='2' AND ispart<>2 AND ishidden<>1  ORDER BY sortrank ASC LIMIT 20</font>
Time2021-01-31 22:31:12
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typenameen,typedir,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                                            FROM `dede_arctype` WHERE  id IN(7,7) AND ispart<>2 AND ishidden<>1  ORDER BY sortrank ASC LIMIT 20</font>
Time2021-01-31 22:31:12
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typenameen,typedir,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                                            FROM `dede_arctype` WHERE  id IN(8,8) AND ispart<>2 AND ishidden<>1  ORDER BY sortrank ASC LIMIT 20</font>
Time2021-01-31 22:31:12
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typenameen,typedir,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                                            FROM `dede_arctype` WHERE  id IN(11,11) AND ispart<>2 AND ishidden<>1  ORDER BY sortrank ASC LIMIT 20</font>
Time2021-01-31 22:31:12
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typenameen,typedir,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath
          From `dede_arctype` WHERE reid=0 And ishidden<>1 order by sortrank asc    </font>
Time2021-01-31 22:31:12
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typenameen,typedir,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath
          From `dede_arctype` WHERE reid=0 And ishidden<>1 order by sortrank asc    </font>
Time2021-01-31 22:31:12
*/
?>
